#pragma once

#include "framework.hpp"
#include <iostream>
#include <string>
#include <conio.h>
#include <thread>
#include <chrono>
#include <psapi.h>
#include <cctype>      
#include <fstream>
#include <vector>
#include <limits>
#include <filesystem>
#include <ios>
#include <sstream>
#include "GlobalVars.hpp"
#include "shellapi.h"
#include <format>
#include "../util/util.hpp"